version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.1.0"
    steps:
      - checkout
      - run:
          name: Install Carthage Dependencies
          command: carthage bootstrap --use-ssh --platform ios
      - run:
          name: Run Tests
          command: xcodebuild -project Parchment.xcodeproj -scheme "Parchment" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.1' test
          
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
